name: rtcc_client_flutter
description: Flutter client SDK for real-time collaboration
version: 0.1.0
homepage: https://github.com/yourusername/real-time-collaboration-sdk

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^2.4.0
  uuid: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test: ^1.24.0

flutter:
  # This package is a pure Dart package