name: Publish to NPM

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Install dependencies
        run: npm install --legacy-peer-deps
        
      - name: Build packages
        run: |
          # Build packages in dependency order
          echo "Building @rtcc/core..."
          cd packages/core && npm run build
          
          echo "Building @rtcc/client-web..."
          cd ../client-web && npm run build
          
          echo "Building @rtcc/server..."
          cd ../server && npm run build
          
          echo "Building @rtcc/react-hooks..."
          cd ../react-hooks && npm run build
        
      - name: Publish to NPM
        run: |
          set -e
          
          # Configure npm to use the token
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          
          # Publish packages in dependency order
          echo "Publishing @rtcc/core..."
          cd $GITHUB_WORKSPACE/packages/core && npm publish --access public
          
          echo "Publishing @rtcc/client-web..."
          cd $GITHUB_WORKSPACE/packages/client-web && npm publish --access public
          
          echo "Publishing @rtcc/server..."
          cd $GITHUB_WORKSPACE/packages/server && npm publish --access public
          
          echo "Publishing @rtcc/react-hooks..."
          cd $GITHUB_WORKSPACE/packages/react-hooks && npm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN_SAAS_DEV_KIT }}